# Generated by Django 4.2.7 on 2023-11-09 18:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avto',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('c0a91b86-cd1b-430e-b9c5-8fbbd573d465'), primary_key=True, serialize=False)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('info', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
